// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using learnapp.Data;

namespace learnapp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846");

            modelBuilder.Entity("learnapp.Model.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("House");

                    b.Property<string>("Street");

                    b.HasKey("Id");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("learnapp.Model.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("AddressId");

                    b.Property<string>("Department");

                    b.Property<string>("FirstName");

                    b.Property<string>("Function");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("Employees");

                    b.HasData(
                        new { Id = new Guid("fafa34af-1325-4310-bf83-8c1379f0019d"), Department = "Estonian", FirstName = "Vaidas", Function = "Developer", LastName = "Brazionis" },
                        new { Id = new Guid("287a58ad-aa56-4eb8-a18c-4dae14cfee72"), Department = "Design", FirstName = "Jonas", Function = "Manager", LastName = "Paulauskas" },
                        new { Id = new Guid("45f60630-4255-4153-9079-98e8323c4034"), Department = "Design", FirstName = "Domas", Function = "Web designer", LastName = "Zemaitis" },
                        new { Id = new Guid("b434ecd3-3b13-4fd6-afcd-fc49ed1eb44f"), Department = "Sales", FirstName = "Sima", Function = "Manager", LastName = "Siniavskaja" },
                        new { Id = new Guid("552740d6-05f6-481e-9e3d-76bb938aa21b"), Department = "Sales", FirstName = "Algimantas", Function = "Sales support", LastName = "Jonauskas" },
                        new { Id = new Guid("a3b1906d-7bdf-41f2-8132-35b56ef3f8b3"), Department = "Lithuanian", FirstName = "Algis", Function = "Developer", LastName = "Ramanauskas" }
                    );
                });

            modelBuilder.Entity("learnapp.Model.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ProjectId");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new { Id = new Guid("9583be43-a77d-4301-bf2c-e5856d6ab678"), ProjectId = "001", Title = "Resmap dev" },
                        new { Id = new Guid("9c61b8dd-9dfd-4ac1-93c0-93147283a053"), ProjectId = "002", Title = "Web design" },
                        new { Id = new Guid("eb98ea74-1971-4275-8d64-3a95f476a0dc"), ProjectId = "003", Title = "Azure impl" }
                    );
                });

            modelBuilder.Entity("learnapp.Model.ProjectTag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("ResourceId");

                    b.Property<Guid>("TagId");

                    b.HasKey("Id");

                    b.HasIndex("ResourceId");

                    b.HasIndex("TagId");

                    b.ToTable("ProjectTag");
                });

            modelBuilder.Entity("learnapp.Model.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new { Id = new Guid("c22e3f0b-ff39-481f-8f69-354d0282042a"), Title = "Web" },
                        new { Id = new Guid("644a70dc-565d-4942-8c5b-dc4e04a77c98"), Title = "Front-end" },
                        new { Id = new Guid("bcd6801a-3aaf-47ad-8700-4bb24630ce18"), Title = "Back-end" },
                        new { Id = new Guid("375e3f64-34dc-484d-b066-be1139156745"), Title = "Design" },
                        new { Id = new Guid("c7dc2b71-ae9e-477a-867b-745eaa676824"), Title = "C#" },
                        new { Id = new Guid("968bc481-63c9-43c9-ba4a-fe94b4869726"), Title = "JavaScript" },
                        new { Id = new Guid("420e0f74-7602-4e61-975c-9f9146301469"), Title = "Java" }
                    );
                });

            modelBuilder.Entity("learnapp.Model.Employee", b =>
                {
                    b.HasOne("learnapp.Model.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");
                });

            modelBuilder.Entity("learnapp.Model.ProjectTag", b =>
                {
                    b.HasOne("learnapp.Model.Project", "Resource")
                        .WithMany("ProjectTags")
                        .HasForeignKey("ResourceId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("learnapp.Model.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
